"""Add processing_time and failure_reason to notes table

Revision ID: ef2c365303c7
Revises: 79ec56e7fef5
Create Date: 2025-09-12 14:28:18.632740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2c365303c7'
down_revision: Union[str, Sequence[str], None] = '79ec56e7fef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('processing_time_ms', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('failure_reason', sa.String(length=512), nullable=True))
    op.alter_column('notes', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_notes_owner_id'), 'notes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notes_status'), 'notes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_status'), table_name='notes')
    op.drop_index(op.f('ix_notes_owner_id'), table_name='notes')
    op.alter_column('notes', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('notes', 'failure_reason')
    op.drop_column('notes', 'processing_time_ms')
    # ### end Alembic commands ###
